### ISSUE TITLE
Page down

### ISSUE THREAD

**Issue by masonnixon** [poliastro/poliastro.github.io#18] opened 2018-09-17 22:13 UTC
Possibly DNS issue. In Chrome:

"This site can’t be reached
blog.poliastro.space’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN"

**Comment by astrojuanlu** [comment] 2018-09-18 04:57
Hi @masonnixon, thanks for reporting! I can't reproduce the issue neither in Chromium nor Firefox (Linux), can you try these steps? https://www.wiknix.com/how-to-fix-dns_probe_finished_nxdomain-in-chrome/

**Comment by astrojuanlu** [comment] 2018-09-18 05:11
Also, in case it helps I fixed an SSL mixed content warning.

**Comment by masonnixon** [comment] 2018-09-18 13:12
Still looks to be inaccessible on my end. I am behind a firewall, so maybe
that is the issue. Do you have an alternate URL I could try?


Cheers,
Mason

**Comment by astrojuanlu** [comment] 2018-09-18 15:00
I'm going to try this solution https://community.cloudflare.com/t/github-pages-route-53-cloudflare-dns-probe-finished-nxdomain/24521/2 this evening, will keep you posted

**Comment by astrojuanlu** [comment] 2018-09-19 07:02
I amended a small issue with the DNS, could you please try again?

**Comment by masonnixon** [comment] 2018-09-19 16:06
Looks like it is still inaccessible. "ERR_NAME_NOT_RESOLVED"


Cheers,
Mason

**Comment by astrojuanlu** [comment] 2018-09-19 16:26
Ok, now it's broken for me as well :gun: Working on it

**Comment by astrojuanlu** [comment] 2018-09-19 16:34
Could you please try again?

**Comment by masonnixon** [comment] 2018-09-20 17:52
Negative. Still no dice.


Cheers,
Mason

**Comment by astrojuanlu** [comment] 2018-09-20 17:54
I assume you are back to the first error, `DNS_PROBE_FINISHED_NXDOMAIN`.

I don't know what else to do on my side, so I fear I will need you to run more diagnostics.

**Comment by masonnixon** [comment] 2018-09-20 19:31
I can try. More than likely the .space domain is blacklisted in the
firewall for some reason. Do you have an alternate address I could try that
is not under that DNS?


Cheers,
Mason

**Comment by astrojuanlu** [comment] 2018-09-21 10:20
Your best bet is to read the files directly on GitHub then:

https://github.com/poliastro/poliastro.github.io/blob/sources/content/articles/2018-06-04-poliastro-python-astronomy-2018-conference.md

**Comment by masonnixon** [comment] 2018-09-23 03:41
Roger. Thanks for looking into this. Fortunately the PDF guide and Jupyter
notebooks in the repo have gotten me to where I could complete my project.
Love the work you guys are doing! Would love to see more Earth-based
coordinate systems support as well.


Cheers,
Mason

**Comment by astrojuanlu** [comment] 2018-09-23 09:40
Thanks to you for your kind words! Earth-based systems have been out of scope for a while because we wanted to make a very general package (which is a bit of a challenge sometimes). This situation might change in mid-2019, but there's still some work we have to do to get there.

With your permission I will close this issue since it does not seem to be a poliastro.github.io problem, feel free to ask further questions about this or other things.

**Closed as completed by astrojuanlu** 2018-09-23 09:40 UTC
